### ISSUE TITLE
Issues upgrading to v4.0.0

### ISSUE THREAD

**Issue by bblia** [airbnb/DeepLinkDispatch#243]
Trying to update to v4.0.0 based on https://github.com/airbnb/DeepLinkDispatch/issues/222#issuecomment-458737266

but getting the below exceptions causing gradle sync to fail:

![image](https://user-images.githubusercontent.com/4870878/51948662-3c20b880-23de-11e9-82b1-4f92240ad597.png)

**Comment by felipecsl** [comment]
did you forget to add `mavenCentral()` to your gradle dependencies?
I can see the archives there already http://repo1.maven.org/maven2/com/airbnb/deeplinkdispatch/4.0.0/

**Comment by rossbacher** [comment]
I didn't anticipate how long the sync can take and published the release on github a bit prematurely. It should all be good now.

**Comment by rossbacher** [comment]
Actually I see there is a problem with the release. :-( Investigating right now.

**Comment by bblia** [comment]
![image](https://user-images.githubusercontent.com/4870878/51950072-e8b16900-23e3-11e9-9567-0f02de35c257.png)

**Comment by bblia** [comment]
Appreciate it -- thank you!

**Comment by rossbacher** [comment]
Fixed with https://github.com/airbnb/DeepLinkDispatch/pull/244

**Comment by rossbacher** [comment]
4.1.0-SNAPSHOT is already available and I verified the fix. I just published 4.1.0 but it might take a while until it is synced to central.

**Comment by ron-steiner** [comment]
spot on @bblia

**Comment by bblia** [comment]
Still not seeing it but i'll wait a while longer -- I shouldn't need mavenCentral() if i have jCenter() right?

**Comment by rossbacher** [comment]
I just build our app with it 

> Still not seeing it but i'll wait a while longer -- I shouldn't need mavenCentral() if i have jCenter() right?

I just build it with right now. And it is here: https://repo1.maven.org/maven2/com/airbnb/deeplinkdispatch/

**Comment by bblia** [comment]
YAY it works here now as well. Thank you very much @rossbacher !!
