### ISSUE TITLE
Incremental annotation processing

### ISSUE THREAD

**Issue by markchristopherng** [airbnb/DeepLinkDispatch#247]
Hi,

Does this project support incremental annotation processing? If not are there any plans to support it to help improve build speed.

**Comment by markchristopherng** [comment]
@elihart I am just wondering if you will have time to look into this, since you mentioned that it might not require a code change?

**Comment by kraghu** [comment]
Has any one have a solution to this ? We are unable to update our libraries because of this

**Comment by marcosalis** [comment]
Anything new on the above? We're unfortunately blocked on using incremental annotation processing with `kapt` because of the library.
Thank you! 🙏

**Comment by radityagumay** [comment]
Hi any updates on this?

**Comment by elihart** [comment]
When there is an update it will be shared.

In the meantime, feel free to contribute a PR to add incremental support if you want it. It should be fairly straightforward - I believe this would simply be an aggregating processor

**Comment by benjamin-bader** [comment]
I just took a stab at this, and I don't believe it will be simple.  The issue is that aggregating processors may only support annotations with `CLASS` or `RUNTIME` retention.  Any processors declaring themselves to be aggregating, and which declare support for `SOURCE` annotations, will cause a build failure.

That's the case with the `DeepLinkProcessor`.  It declares support for `"*"`, which means every annotation on the classpath.  I assume this is to support `@DeepLinkSpec`.  I'm not sure how it will be possible to support arbitrary "qualified" spec annotations and still be an aggregating processor.

It seems like it _should_ be possible; I think dagger-compiler is an incremental processor, but I've no idea how they manage it.  Maybe their processors just don't "consume" `@Qualifier`-annotated things - if so, they're of no help here.

**Comment by LachlanMcKee** [comment]
I believe I have a solution for making the processor incremental (aggregating): https://github.com/airbnb/DeepLinkDispatch/pull/266

This would require users to specify their custom annotations within the build.gradle. Currently I have made it mandatory in the PR, but it could be an optional feature that allowed developers to opt-in to incremental processing.

**Comment by LachlanMcKee** [comment]
In case anyone is interested, I have compiled the binaries on Jitpack (hopefully that's okay). I've tested it out in my current project, and it works a treat :)

```gradle
com.github.LachlanMcKee.DeepLinkDispatch:deeplinkdispatch:4.3.0-INCREMENTAL
com.github.LachlanMcKee.DeepLinkDispatch:deeplinkdispatch-processor:4.3.0-INCREMENTAL
```

**Comment by benjamin-bader** [comment]
@elihart in the absence of any comment from the colleagues you've repeatedly mentioned, can you provide any feedback on the linked PR?  Can you say why it hasn't been merged?

I'm sure it's just that folks are busy with wrapping up their Q4 before the holidays, but it would be nice to hear something nevertheless.  Thanks!

**Comment by elihart** [comment]
People are just busy - they are currently working on optimizing the runtime performance of the library, among other things. We will get to it

**Comment by LachlanMcKee** [comment]
@elihart now that this has been merged, the master README suggests that the feature is live, however it is not. This might be quite confusing. Might be worth either doing a release purely with this change, or reverting the README change for now.

**Comment by elihart** [comment]
@rossbacher is very close to having a large update available to the library. I'll let him decide how to handle this

**Comment by LachlanMcKee** [comment]
@rossbacher now that your PR has been merged in, do you think it would be worthwhile cutting a release?

**Comment by rossbacher** [comment]
@LachlanMcKee  Sorry we were out here until yesterday. I just released `5.0.0-beta01` please give it a try. We decided to go beta with this as we totally rewrote the matcher (in addition to your changes) and as it is working totally different we don't know if we covered all existing use cases. It is passing all existing tests, but be are trying to be safe with this.

**Comment by condesales** [comment]
@rossbacher 
When adding the extra arguments to kapt I still get the following warning:
```
warning: The following options were not recognized by any processor: '[deepLink.incremental, deepLink.customAnnotations, kapt.kotlin.generated]'
```
Does that mean the incremental processing is not working for the library?
I'm using 5.1.0

**Comment by allco** [comment]
I'm using 5.4.3 
And having this:

```
warning: The following options were not recognized by any processor: '[kapt.kotlin.generated, deepLink.incremental]'
```

when apply the following to a gradle subproject:

```
kapt {
    arguments {
        arg("deepLink.incremental", "true")
    }
}

dependencies {
    ...
    kapt com.airbnb:deeplinkdispatch-processor:5.4.3
}
```
